spring:
  application:
    name: corems-migrations
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_DB:corems}
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false  # We run Flyway manually

migrations:
  include-mockdata: ${INCLUDE_MOCKDATA:false}
  clean-before-migrate: ${CLEAN_BEFORE_MIGRATE:false}
  repos-path: ${REPOS_PATH:../../repos}
