spring:
  application:
    name: corems-migrations
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/corems}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false  # We run Flyway manually

migrations:
  include-mockdata: ${INCLUDE_MOCKDATA:false}
  clean-before-migrate: ${CLEAN_BEFORE_MIGRATE:false}
  repos-path: ${REPOS_PATH:../../repos}
